# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_prepare = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_prepare.setEnabled(False)
        self.btn_prepare.setObjectName("btn_prepare")
        self.horizontalLayout.addWidget(self.btn_prepare)
        self.btn_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_filter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_filter.setEnabled(False)
        self.btn_filter.setCheckable(True)
        self.btn_filter.setObjectName("btn_filter")
        self.horizontalLayout.addWidget(self.btn_filter)
        self.btn_filter_settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_filter_settings.setEnabled(False)
        self.btn_filter_settings.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_filter_settings.setObjectName("btn_filter_settings")
        self.horizontalLayout.addWidget(self.btn_filter_settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.user_list = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_list.sizePolicy().hasHeightForWidth())
        self.user_list.setSizePolicy(sizePolicy)
        self.user_list.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.user_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.user_list.setSortingEnabled(True)
        self.user_list.setObjectName("user_list")
        self.user_list.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.user_list)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter1 = QtWidgets.QSplitter(self.tab_3)
        self.splitter1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter1.sizePolicy().hasHeightForWidth())
        self.splitter1.setSizePolicy(sizePolicy)
        self.splitter1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter1.setObjectName("splitter1")
        self.post_list = QtWidgets.QTableView(self.splitter1)
        self.post_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.post_list.setSortingEnabled(True)
        self.post_list.setObjectName("post_list")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter1)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_comments = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_comments.setObjectName("btn_comments")
        self.verticalLayout_2.addWidget(self.btn_comments)
        self.comments_list = QtWidgets.QTableView(self.verticalLayoutWidget_2)
        self.comments_list.setObjectName("comments_list")
        self.verticalLayout_2.addWidget(self.comments_list)
        self.gridLayout_4.addWidget(self.splitter1, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setAccessibleName("")
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.follower_list = QtWidgets.QTableView(self.tab)
        self.follower_list.setEnabled(True)
        self.follower_list.setObjectName("follower_list")
        self.gridLayout_2.addWidget(self.follower_list, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.following_list = QtWidgets.QTableView(self.tab_2)
        self.following_list.setEnabled(True)
        self.following_list.setObjectName("following_list")
        self.horizontalLayout_2.addWidget(self.following_list)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setEnabled(True)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load = QtWidgets.QAction(MainWindow)
        self.action_load.setObjectName("action_load")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_settngs = QtWidgets.QAction(MainWindow)
        self.action_settngs.setObjectName("action_settngs")
        self.action_login = QtWidgets.QAction(MainWindow)
        self.action_login.setEnabled(True)
        self.action_login.setObjectName("action_login")
        self.action_logout = QtWidgets.QAction(MainWindow)
        self.action_logout.setObjectName("action_logout")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.menu.addAction(self.action_import)
        self.menu.addAction(self.action_export)
        self.menu.addSeparator()
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_load)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.action_settngs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ИнстаПарсер"))
        self.btn_prepare.setText(_translate("MainWindow", "Обработать"))
        self.btn_stop.setText(_translate("MainWindow", "Остановить"))
        self.btn_filter.setText(_translate("MainWindow", "Фильтр"))
        self.btn_filter_settings.setText(_translate("MainWindow", "..."))
        self.btn_comments.setText(_translate("MainWindow", "Загрузить комментарии"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Посты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Подписчики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Подписки"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Настройки"))
        self.action_load.setText(_translate("MainWindow", "Загрузить проект"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_settngs.setText(_translate("MainWindow", "Настройки"))
        self.action_login.setText(_translate("MainWindow", "Подключиться"))
        self.action_logout.setText(_translate("MainWindow", "Отключится"))
        self.action_save.setText(_translate("MainWindow", "Сохранить проект"))
        self.action_export.setText(_translate("MainWindow", "Экспорт пользователей"))
        self.action_import.setText(_translate("MainWindow", "Импорт пользователей"))

